// Do not edit. This file is machine generated by the Resource DLL Wizard.

library FTPDBWebClient;

{ITE} {DFMFileType} {ServerController.dfm}
{ITE} {DFMFileType} {Unit1.dfm}
{ITE} {DFMFileType} {Unit2.dfm}
{ITE} {DFMFileType} {Unit4.dfm}
{ITE} {DFMFileType} {Unit5.dfm}
{ITE} {DFMFileType} {Unit6.dfm}
{ITE} {DFMFileType} {UserSessionUnit.dfm}
{ITE} {RCFileType} {FTPDBWebClient_DRC.rc}

{$R 'ServerController.dfm' IWServerController:TForm(IWServerControllerBase)}
{$R 'Unit1.dfm' IWFormLogin:TForm(IWAppForm)}
{$R 'Unit2.dfm' IWFormMain:TForm(IWAppForm)}
{$R 'Unit4.dfm' IWFormLog:TForm(IWAppForm)}
{$R 'Unit5.dfm' IWFormAdmin:TForm(IWAppForm)}
{$R 'Unit6.dfm' IWFormOptions:TForm(IWAppForm)}
{$R 'UserSessionUnit.dfm' IWUserSession:TForm(IWUserSessionBase)}
{$R 'FTPDBWebClient_DRC.res' 'FTPDBWebClient_DRC.rc'}

{$E ENU}

begin
end.