// Do not edit. This file is machine generated by the Resource DLL Wizard.

library FTPDBCP;

{ITE} {DFMFileType} {vcl\DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl\DBPWDLG.dfm}
{ITE} {DFMFileType} {Applet.dfm}
{ITE} {DFMFileType} {DataModuleFTPDBDCP.dfm}
{ITE} {RCFileType} {FTPDBCP_DRC.rc}

{$R 'vcl\DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl\DBPWDLG.dfm' PasswordDialog:TForm(Form)}
{$R 'Applet.dfm' AppletModule1:TAppletModule}
{$R 'DataModuleFTPDBDCP.dfm' DataModuleFTPDBDaemon:TDataModule}
{$R 'FTPDBCP_DRC.res' 'FTPDBCP_DRC.rc'}

{$E RUS}

begin
end.