CREATE TABLE "FTP_HOST"
(
  "KOD"	INTEGER NOT NULL,
  "HOST"	VARCHAR(50) CHARACTER SET WIN1251,
  "MAXLINEACTION"	SMALLINT default 1,
  "MAXLINELENGTH"	INTEGER default 16384,
  "PASSIVE"	SMALLINT default 1,
  "PORT"	SMALLINT default 21,
  "RECVBUFFERSIZE"	INTEGER default 32768,
  "SENDBUFFERSIZE"	INTEGER default 32768,
  "TRANSFERTYPE"	SMALLINT default 1,
 PRIMARY KEY ("KOD")
);
ALTER TABLE "FTP_HOST" ADD FOREIGN KEY ("MAXLINEACTION") REFERENCES S_MAXLINEACTION ("KOD");
ALTER TABLE "FTP_HOST" ADD FOREIGN KEY ("PASSIVE") REFERENCES S_BLN ("KOD");
ALTER TABLE "FTP_HOST" ADD FOREIGN KEY ("TRANSFERTYPE") REFERENCES S_TRANSFERTYPE ("KOD");

CREATE TABLE "FTP_FILES"
(
  "HOST"    INTEGER,
  "A_ALL"   VARCHAR(600) CHARACTER SET WIN1251,
  "A_PATH"  VARCHAR(500) CHARACTER SET WIN1251,
  "A_ATR"   VARCHAR(10) CHARACTER SET WIN1251,
  "A_USER"  INTEGER,
  "A_GROUP" INTEGER,
  "A_SIZE"  INTEGER,
  "A_DATE"  DATE,
  "A_TIME"  TIME,
  "A_NAME"  VARCHAR(300) CHARACTER SET WIN1251,
  FOREIGN KEY (host) REFERENCES ftp_host (kod)
);

CREATE TABLE "FTP_DIRECTORIES"
(
  "HOST"    INTEGER,
  "A_ALL"   VARCHAR(600) CHARACTER SET WIN1251,
  "A_PATH"  VARCHAR(500) CHARACTER SET WIN1251,
  "A_ATR"   VARCHAR(10) CHARACTER SET WIN1251,
  "A_USER"  INTEGER,
  "A_GROUP" INTEGER,
  "A_SIZE"  INTEGER,
  "A_DATE"  DATE,
  "A_TIME"  TIME,
  "A_NAME"  VARCHAR(300) CHARACTER SET WIN1251,
  FOREIGN KEY (host) REFERENCES ftp_host (kod)
);

CREATE TABLE "FTP_SCAN1"
(
  "N"	INTEGER NOT NULL,
  "HOST"	INTEGER NOT NULL,
  "DT"	"D_D_NOW",
  "TM"	"D_T_NOW",
 PRIMARY KEY ("N"),
 FOREIGN KEY (host) REFERENCES ftp_host (kod)
);

CREATE TABLE "FTP_LOGIN"
(
  "KOD"	INTEGER NOT NULL,
  "HOST"	INTEGER,
  "LOGIN"	VARCHAR(50) CHARACTER SET WIN1251,
  "PASS"	VARCHAR(50) CHARACTER SET WIN1251,
  "PLOGIN"	VARCHAR(50) CHARACTER SET WIN1251 default '',
  "PPASS"	VARCHAR(50) CHARACTER SET WIN1251 default '',
  "PHOST"	VARCHAR(50) CHARACTER SET WIN1251 default '',
  "PPORT"	SMALLINT default 0,
  "PPROXYTYPE"	SMALLINT default 1,
  "READTIMEOUT"	INTEGER default 0,
  "ACT"         SMALLINT DEFAULT 1,
 PRIMARY KEY ("KOD")
);
ALTER TABLE "FTP_LOGIN" ADD FOREIGN KEY ("PPROXYTYPE") REFERENCES S_PROXYTYPE ("KOD");
ALTER TABLE "FTP_LOGIN" ADD FOREIGN KEY ("ACT") REFERENCES S_BLN(KOD);

CREATE TABLE "FTP_DIRS"
(
  "KOD"	INTEGER NOT NULL,
  "LOGIN"	INTEGER,
  "A_ALL"   VARCHAR(600) CHARACTER SET WIN1251,
  "A_PATH"  VARCHAR(500) CHARACTER SET WIN1251,
  "A_ATR"   VARCHAR(10) CHARACTER SET WIN1251,
  "A_USER"  INTEGER,
  "A_GROUP" INTEGER,
  "A_SIZE"  INTEGER,
  "A_DATE"  DATE,
  "A_TIME"  TIME,
  "A_NAME"  VARCHAR(300) CHARACTER SET WIN1251,
  PRIMARY KEY ("KOD")
  FOREIGN KEY (login) REFERENCES ftp_login (kod)
);

CREATE TABLE "FTP_SCAN2"
(
  "N"	INTEGER NOT NULL,
  "LOGIN"	INTEGER NOT NULL,
  "DT"	"D_D_NOW",
  "TM"	"D_T_NOW",
 PRIMARY KEY ("N"),
 FOREIGN KEY (LOGIN) REFERENCES ftp_login (kod)
);

CREATE TABLE "OPTIONS"
(
  "LOGIN"  VARCHAR(50) CHARACTER SET WIN1251 DEFAULT 'admin',
  "PASS"   VARCHAR(50) CHARACTER SET WIN1251 DEFAULT 'defpass',
  "LAI"    SMALLINT default 2,
  "DAI"    SMALLINT default 2,
  "SRTO"   SMALLINT DEFAULT 5 NOT NULL CHECK ("SRTO" BETWEEN 0 and 60),
  "STO"    SMALLINT DEFAULT 5 NOT NULL CHECK ("STO" BETWEEN 1 and 60),
  "LRL"    INTEGER DEFAULT 100 NOT NULL CHECK ("LRL" BETWEEN 100 and 100000000),
  "LRD"    INTEGER DEFAULT 100 NOT NULL CHECK ("LRL" BETWEEN 100 and 100000000),
  "LRS"    INTEGER DEFAULT 100 NOT NULL CHECK ("LRL" BETWEEN 100 and 100000000),
  "PORT"   INTEGER DEFAULT 8888 NOT NULL CHECK ("PORT" >0),
  "RSN"    SMALLINT default 1,
  "RLIMIT" SMALLINT default 0
 );
ALTER TABLE "OPTIONS" ADD FOREIGN KEY ("LAI") REFERENCES S_BLN ("KOD");
ALTER TABLE "OPTIONS" ADD FOREIGN KEY ("DAI") REFERENCES S_BLN ("KOD");
ALTER TABLE "OPTIONS" ADD FOREIGN KEY ("RSN") REFERENCES S_BLN ("KOD");
ALTER TABLE "OPTIONS" ADD FOREIGN KEY ("RLIMIT") REFERENCES S_ROWLIMIT ("KOD");

INSERT INTO "OPTIONS" ("LOGIN") VALUES ('admin');

CREATE TABLE "DIRS_SNHR"
(
  "KOD"	INTEGER NOT NULL,
  "HOST"      INTEGER NOT NULL,
  "A_PATH"    VARCHAR(600) CHARACTER SET WIN1251, 
  "L_PATH"    VARCHAR(600) CHARACTER SET WIN1251,
  "DIRECTION" SMALLINT DEFAULT 2,
  "PARAMS"    SMALLINT DEFAULT 0,
  PRIMARY KEY ("KOD"),
  FOREIGN KEY (host) REFERENCES ftp_host (kod)
);
ALTER TABLE DIRS_SNHR ADD FOREIGN KEY (DIRECTION) REFERENCES S_BLN(KOD);
ALTER TABLE DIRS_SNHR ADD FOREIGN KEY (PARAMS) REFERENCES S_PARAMS(KOD);

CREATE TABLE "FTP_SCAN3"
(
  "N"	INTEGER NOT NULL,
  "HOST"	INTEGER NOT NULL,
  "DT"	"D_D_NOW",
  "TM"	"D_T_NOW",
  "TEXT" VARCHAR(600) CHARACTER SET WIN1251, 
 PRIMARY KEY ("N"),
 FOREIGN KEY (host) REFERENCES ftp_host (kod)
);